version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/adless
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
      - -X main.gitCommit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

# brews:
#   - repository:
#       owner: WittyJudge
#       name: homebrew-adless
#     directory: Formula
#     homepage: https://github.com/WIttyJudge/homebrew-adless
#     description: Local domains blocker written in Go
#     license: Apache License 2.0

# nfpms:
#   - id: adless-packages
#     file_name_template: >-
#       {{ .ProjectName }}_
#       {{- .Tag }}_
#       {{- if eq .Arch "amd64" }}x86_64
#       {{- else if eq .Arch "386" }}i386
#       {{- else }}{{ .Arch }}{{ end }}
#     homepage: https://github.com/WIttyJudge/adless
#     description: Local domains blocker written in Go  
#     maintainer: WittyJudge
#     license: Apache License 2.0
#     vendor: adless
#     formats:
#       - deb
#       - rpm

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'
